# Generated by Django 2.1.7 on 2019-03-25 14:19

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_importance',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=projects.models.default_task_importance),
        ),
        migrations.AddField(
            model_name='workflow',
            name='task_importance',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=projects.models.default_task_importance),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
