# Generated by Django 2.1.7 on 2019-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190325_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='instructions',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
