# Generated by Django 2.1.7 on 2019-03-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190326_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Med'), (3, 'Low')], null=True, verbose_name='Project Priority'),
        ),
        migrations.AlterField(
            model_name='request',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Med'), (3, 'Low')], null=True, verbose_name='Request Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Med'), (3, 'Low')], null=True, verbose_name='Task Priority'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Med'), (3, 'Low')], null=True, verbose_name='Workflow Priority'),
        ),
    ]
