# Generated by Django 2.1.7 on 2019-03-27 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_auto_20190326_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='ranks',
            field=models.ManyToManyField(related_name='project_ranks', through='projects.ProjectRank', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='ranks',
            field=models.ManyToManyField(related_name='task_ranks', through='projects.TaskRank', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='ranks',
            field=models.ManyToManyField(related_name='workflow_ranks', through='projects.WorkflowRank', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workflowrank',
            unique_together={('user', 'workflow', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='taskrank',
            unique_together={('user', 'task', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='projectrank',
            unique_together={('user', 'project', 'rank')},
        ),
    ]
