# Generated by Django 2.1.7 on 2019-03-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190327_1132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrank',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taskrank',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workflowrank',
            unique_together=set(),
        ),
    ]
