# Generated by Django 2.1.7 on 2019-03-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190328_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(0, 'No importance'), (1, 'Low'), (2, 'Med'), (3, 'High')], default=0, null=True, verbose_name='Project Priority'),
        ),
        migrations.AlterField(
            model_name='request',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(0, 'No importance'), (1, 'Low'), (2, 'Med'), (3, 'High')], default=0, null=True, verbose_name='Request Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(0, 'No importance'), (1, 'Low'), (2, 'Med'), (3, 'High')], default=0, null=True, verbose_name='Task Priority'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(0, 'No importance'), (1, 'Low'), (2, 'Med'), (3, 'High')], default=0, null=True, verbose_name='Workflow Priority'),
        ),
    ]
