# Generated by Django 2.1.7 on 2019-04-09 05:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190330_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pre_save_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Backend flag', null=True),
        ),
    ]
