# Generated by Django 2.1.7 on 2019-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190502_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_email_notified',
            field=models.BooleanField(default=False, verbose_name='Is Email Modified'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_email_notified',
            field=models.BooleanField(default=False, verbose_name='Is Email Modified'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_email_notified',
            field=models.BooleanField(default=False, verbose_name='Is Email Modified'),
        ),
    ]
