# Generated by Django 2.1.7 on 2019-06-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20190415_1123'),
        ('projects', '0012_auto_20190517_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='attachment',
            name='document_tags',
            field=models.ManyToManyField(blank=True, related_name='document_tags', to='projects.Tag', verbose_name='Document Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_organization', to='authentication.Organization', verbose_name='Organization Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Tag'),
        ),
    ]
