# Generated by Django 2.1.7 on 2019-06-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_audithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='audithistory',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_to', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
        migrations.AlterField(
            model_name='audithistory',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_by', to=settings.AUTH_USER_MODEL, verbose_name='By User'),
        ),
    ]
