# Generated by Django 2.1.7 on 2019-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190628_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='audithistory',
            name='model_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='old_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='old_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='old_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
