# Generated by Django 2.1.7 on 2019-07-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20190705_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='audithistory',
            name='last_importance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='audithistory',
            name='old_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Old Due Date'),
        ),
    ]
