# Generated by Django 2.1.7 on 2019-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20190705_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='audithistory',
            name='new_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='new Due Date'),
        ),
    ]
