# Generated by Django 2.1.7 on 2019-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_audithistory_new_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='document_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
