# Generated by Django 2.1.7 on 2019-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_audithistory_new_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Is Delete'),
        ),
    ]
