# Generated by Django 2.1.7 on 2019-07-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_attachment_document_name'),
        ('projects', '0019_attachment_is_delete'),
    ]

    operations = [
    ]
