# Generated by Django 2.1.7 on 2019-07-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20190717_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attorney_client_privilege',
            field=models.BooleanField(default=False, verbose_name='Task                                                     Privilege Attorney Client'),
        ),
        migrations.AddField(
            model_name='task',
            name='confidential_privilege',
            field=models.BooleanField(default=False, verbose_name='Task                                                  Privilege Confidential'),
        ),
        migrations.AddField(
            model_name='task',
            name='work_product_privilege',
            field=models.BooleanField(default=False, verbose_name='Task                                                  Privilege Work Product'),
        ),
    ]
