# Generated by Django 2.1.7 on 2019-07-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20190729_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='attorney_client_privilege',
            field=models.BooleanField(default=False, verbose_name='Workflow                                                     Privilege Attorney Client'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='confidential_privilege',
            field=models.BooleanField(default=False, verbose_name='Workflow                                                  Privilege Confidential'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='work_product_privilege',
            field=models.BooleanField(default=False, verbose_name='Workflow                                                  Privilege Work Product'),
        ),
    ]
