# Generated by Django 2.1.7 on 2019-07-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20190729_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attorney_client_privilege',
            field=models.BooleanField(default=False, verbose_name='Project                                                     Privilege Attorney Client'),
        ),
        migrations.AddField(
            model_name='project',
            name='confidential_privilege',
            field=models.BooleanField(default=False, verbose_name='Project                                                  Privilege Confidential'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_product_privilege',
            field=models.BooleanField(default=False, verbose_name='Project                                                  Privilege Work Product'),
        ),
    ]
