# Generated by Django 2.1.7 on 2019-08-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20190729_2211'),
        ('projects', '0022_auto_20190725_0531'),
    ]

    operations = [
    ]
