# Generated by Django 2.1.7 on 2019-08-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_merge_20190805_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
