# Generated by Django 2.1.7 on 2019-08-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_workflowrank_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskrank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
