# Generated by Django 2.1.7 on 2019-09-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20190916_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroupmember',
            name='name',
        ),
    ]
