# Generated by Django 2.1.7 on 2019-09-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_remove_workgroupmember_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to_group',
            field=models.ManyToManyField(blank=True, related_name='project_assigned_to_workgroup', to='projects.WorkGroup', verbose_name='WorkGroup Project'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to_group',
            field=models.ManyToManyField(blank=True, related_name='task_assigned_to_workgroup', to='projects.WorkGroup', verbose_name='WorkGroup Task'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='assigned_to_group',
            field=models.ManyToManyField(blank=True, related_name='workflow_assigned_to_workgroup', to='projects.WorkGroup', verbose_name='WorkGroup Workflow'),
        ),
    ]
