# Generated by Django 2.1.7 on 2019-10-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20191011_0543'),
        ('projects', '0030_auto_20190920_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('name', models.CharField(db_index=True, max_length=254, verbose_name='Name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='User E-mail Address')),
                ('user_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(blank=True, max_length=226, null=True)),
                ('subject', models.CharField(blank=True, max_length=226, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('requested_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Requested Due Date')),
                ('assigned_to', models.CharField(blank=True, max_length=256, null=True)),
                ('request_priority', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Med'), (3, 'High')], default=2, null=True, verbose_name='Request Priority')),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Access Token Expiration Date')),
                ('is_expire', models.BooleanField(default=False, verbose_name='Is Access Token Expired')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_service_desk', to='authentication.Organization', verbose_name='Company ServiceDesk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='audithistory',
            name='model_reference',
            field=models.CharField(blank=True, choices=[('project', 'Project'), ('workflow', 'Workflow'), ('task', 'Task'), ('attachment', 'Attachment'), ('servicedesk', 'ServiceDesk')], max_length=225, null=True),
        ),
    ]
