# Generated by Django 2.1.7 on 2019-10-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20191015_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In-Progress'), (3, 'Completed'), (4, 'Archived'), (5, 'External Request')], default=1, verbose_name='Status'),
        ),
    ]
