# Generated by Django 2.1.7 on 2019-10-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20191017_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedesk',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Is Request Deleted'),
        ),
        migrations.AddField(
            model_name='task',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_request', to='projects.ServiceDesk', verbose_name='Request To Task'),
        ),
    ]
