# Generated by Django 2.1.7 on 2019-10-19 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20191017_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('document', models.FileField(upload_to='ServiceDeskDocuments/')),
                ('document_name', models.CharField(blank=True, max_length=254, null=True)),
                ('uploaded_by', models.EmailField(max_length=254, verbose_name='Uploader E-mail Address')),
                ('can_remove', models.BooleanField(default=True, verbose_name='Attachment Remove')),
                ('is_delete', models.BooleanField(default=True, verbose_name='Attachment Deleted')),
                ('service_desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_desk_attachment', to='projects.ServiceDesk', verbose_name='Service Desk Attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In-Progress'), (3, 'Completed'), (4, 'Archived'), (5, 'External Request'), (6, 'External Update')], default=1, verbose_name='Status'),
        ),
    ]
