# Generated by Django 2.1.7 on 2019-10-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20191019_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedeskattachment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Attachment Deleted'),
        ),
    ]
