# Generated by Django 2.1.7 on 2019-10-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20191019_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_assignee_changed',
            field=models.BooleanField(default=False, verbose_name='Is Assignee Changed'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_assignee_changed',
            field=models.BooleanField(default=False, verbose_name='Is Assignee Changed'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_assignee_changed',
            field=models.BooleanField(default=False, verbose_name='Is Assignee Changed'),
        ),
    ]
