# Generated by Django 2.1.7 on 2019-11-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_merge_20191105_1252'),
        ('projects', '0036_auto_20191023_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeskRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('name', models.CharField(db_index=True, max_length=254, verbose_name='Name')),
                ('subject', models.CharField(blank=True, max_length=226, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('requested_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Requested Due Date')),
                ('assigned_to', models.CharField(blank=True, max_length=256, null=True)),
                ('request_priority', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Med'), (3, 'High')], default=2, null=True, verbose_name='Request Priority')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Is Request Deleted')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDeskUserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('user_email', models.EmailField(max_length=254, verbose_name='E-mail Address')),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Access Token Expiration Date')),
                ('is_expire', models.BooleanField(default=False, verbose_name='Is Access Token Expired')),
                ('user_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(blank=True, max_length=226, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_service_desk_user', to='authentication.Organization', verbose_name='Company ServiceDesk User Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicedeskrequest',
            name='user_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_desk_user', to='projects.ServiceDeskUserInformation', verbose_name='ServiceDesk User'),
        ),
        migrations.AddField(
            model_name='servicedeskattachment',
            name='service_desk_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_desk_request_attachment', to='projects.ServiceDeskRequest', verbose_name='Service Desk Attachment'),
        ),
    ]
