# Generated by Django 2.1.7 on 2019-11-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20191113_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='servicedesk_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedesk_request_task', to='projects.ServiceDeskRequest', verbose_name='ServiceDeskRequest To Task'),
        ),
    ]
