# Generated by Django 2.1.7 on 2019-11-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_task_servicedesk_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeskuserinformation',
            name='user_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
