# Generated by Django 2.1.7 on 2019-11-18 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0039_servicedeskuserinformation_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeskExternalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('replies', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_request_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_servicedeskrequest', to='projects.Project', verbose_name='ServiceDesk Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDeskRequestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_message', to='projects.Project', verbose_name='Project Message')),
                ('reply_by_servicedeskuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedeskuser_message', to='projects.ServiceDeskUserInformation', verbose_name='ServiceDeskRequest Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicedeskrequest',
            name='is_internal_request',
            field=models.BooleanField(default=False, verbose_name='Is Internal Request'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Task Delete'),
        ),
        migrations.AddField(
            model_name='servicedeskrequestmessage',
            name='servicedesk_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedesk_request_message', to='projects.ServiceDeskRequest', verbose_name='ServiceDeskRequest Message'),
        ),
        migrations.AddField(
            model_name='servicedeskrequestmessage',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_message', to='projects.Task', verbose_name='Task Message'),
        ),
        migrations.AddField(
            model_name='servicedeskrequestmessage',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_message', to='projects.Workflow', verbose_name='Workflow Message'),
        ),
        migrations.AddField(
            model_name='servicedeskexternalrequest',
            name='service_desk_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_desk_external_request', to='projects.ServiceDeskRequest', verbose_name='ServiceDesk External Request'),
        ),
        migrations.AddField(
            model_name='servicedeskexternalrequest',
            name='servicedeskuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_to_servicedeskrequest', to='projects.ServiceDeskUserInformation', verbose_name='ServiceDesk Task User'),
        ),
        migrations.AddField(
            model_name='servicedeskexternalrequest',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_servicedeskrequest', to='projects.Task', verbose_name='ServiceDesk Task'),
        ),
        migrations.AddField(
            model_name='servicedeskexternalrequest',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_servicedeskrequest', to='projects.Workflow', verbose_name='ServiceDesk Workflow'),
        ),
    ]
