# Generated by Django 2.1.7 on 2019-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20191118_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Completed'), (3, 'Archived'), (4, 'External Request'), (5, 'External Update')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Completed'), (3, 'Archived'), (4, 'External Request'), (5, 'External Update')], default=1, verbose_name='Status'),
        ),
    ]
