# Generated by Django 2.1.7 on 2019-12-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_tagchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagchangelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tag', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='tagchangelog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_tag', to='projects.Task'),
        ),
        migrations.AddField(
            model_name='tagchangelog',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tag', to='projects.Workflow'),
        ),
    ]
