# Generated by Django 2.1.7 on 2019-12-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20191219_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWorkLoadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('category_type', models.CharField(blank=True, choices=[('project', 'Project'), ('workflow', 'Workflow'), ('task', 'Task')], max_length=225, null=True)),
                ('new', models.IntegerField(blank=True, default=0, null=True)),
                ('completed', models.IntegerField(blank=True, default=0, null=True)),
                ('changed_at', models.DateField(blank=True, db_index=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_workload', to='projects.Project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_workload', to='projects.Task')),
                ('work_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_workload', to='projects.WorkGroup')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_workload', to='projects.Workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
