# Generated by Django 2.1.7 on 2019-12-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_teammemberworkloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagchangelog',
            name='tag_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_log', to='projects.Tag'),
        ),
    ]
