# Generated by Django 2.1.7 on 2019-12-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_workproductivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is Private'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is Private'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is Private'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
    ]
