# Generated by Django 2.1.7 on 2019-12-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20191231_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='completed_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
