# Generated by Django 2.1.7 on 2020-01-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20191231_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='message_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedesk_message_attachment', to='projects.ServiceDeskRequestMessage'),
        ),
        migrations.AddField(
            model_name='servicedeskrequestmessage',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Is Message Deleted'),
        ),
        migrations.AddField(
            model_name='servicedeskrequestmessage',
            name='is_external_message',
            field=models.BooleanField(default=False, verbose_name='Is External Message'),
        ),
        migrations.AddField(
            model_name='servicedeskrequestmessage',
            name='is_internal_message',
            field=models.BooleanField(default=False, verbose_name='Is Internal Message'),
        ),
    ]
