# Generated by Django 2.1.7 on 2020-03-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_taskrank_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeskrequestmessage',
            name='is_first_message',
            field=models.BooleanField(default=False, verbose_name='Is First Message'),
        ),
    ]
