# Generated by Django 2.1.7 on 2020-04-24 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0058_servicedeskrequestmessage_is_first_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeskExternalCCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail Address')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('external_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associate_external_request', to='projects.ServiceDeskExternalRequest', verbose_name='Service Desk External Request')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_message', to='projects.ServiceDeskRequestMessage', verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
