# Generated by Django 2.1.7 on 2020-04-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_servicedeskexternalccuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In-Progress'), (3, 'Completed'), (4, 'Archived'), (5, 'External Request'), (6, 'External Update'), (7, 'Advise'), (8, 'Analyze'), (9, 'Approve'), (10, 'Brief'), (11, 'Closing'), (12, 'Communicate'), (13, 'Coordinate'), (14, 'Deposition'), (15, 'Diligence'), (16, 'Discovery'), (17, 'Document'), (18, 'Draft'), (19, 'Execute'), (20, 'Fact Gathering'), (21, 'File'), (22, 'File Management'), (23, 'Hearing'), (24, 'Investigate'), (25, 'Negotiate'), (26, 'On Hold'), (27, 'Plan'), (28, 'Pleading'), (29, 'Prepare'), (30, 'Research'), (31, 'Review'), (32, 'Revise'), (33, 'Settle'), (34, 'Structure')], default=1, verbose_name='Status'),
        ),
    ]
