# Generated by Django 2.2.17 on 2021-07-19 14:35

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_awscredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='external_url',
            field=models.URLField(
                blank=True,
                null=True,
                validators=[projects.models.attachments.validate_attachment_external_url],
                verbose_name='External URL',
            ),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
    ]
