# Generated by Django 2.2.17 on 2021-10-18 05:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import projects.globalcustomfields.models.globalcustomfields
from django.db.models import Q


def add_records(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''

    Permission = apps.get_model('authentication', 'Permission')
    Organization = apps.get_model('authentication', 'Organization')
    Group = apps.get_model('authentication', 'Group')
    DefaultPermission = apps.get_model('authentication', 'DefaultPermission')
    GroupAndPermission = apps.get_model('authentication', 'GroupAndPermission')
    permission_category = 'globalcustomfield'
    pers = [
        Permission(
            name='GlobalCustomField View',
            permission_category=permission_category,
            slug='globalcustomfield_globalcustomfield-view',
        ),
        Permission(
            name='GlobalCustomField Create',
            permission_category=permission_category,
            slug='globalcustomfield_globalcustomfield-create',
        ),
        Permission(
            name='GlobalCustomField Update',
            permission_category=permission_category,
            slug='globalcustomfield_globalcustomfield-update',
        ),
        Permission(
            name='GlobalCustomField Destroy',
            permission_category=permission_category,
            slug='globalcustomfield_globalcustomfield-destroy',
        ),
    ]

    GroupAndPermission.objects.filter(permission__permission_category=permission_category).delete()
    DefaultPermission.objects.filter(permission__permission_category=permission_category).delete()
    Permission.objects.filter(permission_category=permission_category).delete()

    if Permission.objects.all().count() > 0 and Group.objects.all().count() > 0 and DefaultPermission.objects.all().count() > 0:
        pers = Permission.objects.bulk_create(
            pers
        )
        for org in Organization.objects.all():
            for group in Group.objects.filter(Q(name='Admin')):
                d_pers = [
                    DefaultPermission(
                        group=group,
                        permission=per,
                        has_permission=True,
                    )
                    for per in pers
                ]
                DefaultPermission.objects.bulk_create(d_pers)

                g_pers = [
                    GroupAndPermission(
                        group=group,
                        permission=per,
                        company=org,
                        has_permission=True,
                    )
                    for per in pers
                ]
                GroupAndPermission.objects.bulk_create(g_pers)


def remove_records(apps, schema_editor):
    Permission = apps.get_model('authentication', 'Permission')
    DefaultPermission = apps.get_model('authentication', 'DefaultPermission')
    GroupAndPermission = apps.get_model('authentication', 'GroupAndPermission')
    permission_category = 'globalcustomfield'
    GroupAndPermission.objects.filter(permission__permission_category=permission_category).delete()
    DefaultPermission.objects.filter(permission__permission_category=permission_category).delete()
    Permission.objects.filter(permission_category=permission_category).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0063_auto_20210910_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=40, verbose_name='Label')),
                ('field_type', models.CharField(choices=[('Text', 'Text'), ('Int', 'Number'), ('Date', 'Date'), ('Currency', 'Currency')], default=projects.globalcustomfields.models.globalcustomfields.GlobalCustomFieldValueType('Text'), max_length=10, verbose_name='Type')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Default value')),
                ('is_required', models.BooleanField(verbose_name='Is required?')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Is archive')),
                ('allow_content_type', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Allow content type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Global custom filed',
                'verbose_name_plural': 'Global custom fields',
            },
        ),
        migrations.CreateModel(
            name='GlobalCustomFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Is archive')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type')),
                ('global_custom_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.GlobalCustomField', verbose_name='Global custom field')),
            ],
            options={
                'verbose_name': 'Global custom field value',
                'verbose_name_plural': 'Global custom field values',
            },
        ),
        migrations.RunPython(
            add_records,
            reverse_code=remove_records,
        ),
    ]
