# Generated by Django 2.2.17 on 2021-11-03 16:17

from django.db import migrations, models
import projects.globalcustomfields.models.globalcustomfields
import projects.tasksapp.models.customfields


def migrate_up_custom_fields_records(apps, schema_editor):
    CustomField = apps.get_model('projects', 'CustomField')
    GlobalCustomField = apps.get_model('projects', 'GlobalCustomField')
    for model in [CustomField, GlobalCustomField]:
        model.objects.filter(field_type='Int').update(field_type='Number')


def migrate_down_custom_fields_records(apps, schema_editor):
    CustomField = apps.get_model('projects', 'CustomField')
    GlobalCustomField = apps.get_model('projects', 'GlobalCustomField')
    for model in [CustomField, GlobalCustomField]:
        model.objects.filter(field_type='Number').update(field_type='Int')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_globalcustomfield_globalcustomfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Date', 'Date'), ('Currency', 'Currency')], default=projects.tasksapp.models.customfields.CustomFieldType('Text'), max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='globalcustomfield',
            name='field_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Date', 'Date'), ('Currency', 'Currency')], default=projects.globalcustomfields.models.globalcustomfields.GlobalCustomFieldValueType('Text'), max_length=10, verbose_name='Type'),
        ),
        migrations.RunPython(
            migrate_up_custom_fields_records,
            migrate_down_custom_fields_records,
        )
    ]
