# Generated by Django 2.2.17 on 2021-12-07 20:36

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import projects.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_auto_20211104_0414'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0067_auto_20211203_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfixture',
            name='workflow_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task_fixtures',
                to='projects.WorkflowTemplate',
                verbose_name='Workflow template',
            ),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='attorney_client_privilege',
            field=models.BooleanField(default=False, verbose_name='Workflow Privilege Attorney Client'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='confidential_privilege',
            field=models.BooleanField(default=False, verbose_name='Workflow Privilege Confidential'),
        ),
        migrations.CreateModel(
            name='WorkflowFixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('name', models.CharField(db_index=True, max_length=254, verbose_name='Name')),
                (
                    'custom_fields_value',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True, verbose_name='Custom fields value'
                    ),
                ),
                (
                    'status',
                    models.IntegerField(
                        choices=[
                            (1, 'Active'),
                            (2, 'Completed'),
                            (3, 'Archived'),
                            (4, 'External Request'),
                            (5, 'External Update'),
                        ],
                        default=1,
                        verbose_name='Status',
                    ),
                ),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('old_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_email_notified', models.BooleanField(default=False, verbose_name='Is Email Modified')),
                ('is_assignee_changed', models.BooleanField(default=False, verbose_name='Is Assignee Changed')),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Due Date')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
                ('completed_percentage', models.IntegerField(blank=True, default=0, null=True)),
                (
                    'importance',
                    models.IntegerField(
                        blank=True,
                        choices=[(0, 'No importance'), (1, 'Low'), (2, 'Med'), (3, 'High')],
                        default=0,
                        null=True,
                        verbose_name='Workflow Priority',
                    ),
                ),
                (
                    'task_importance',
                    django.contrib.postgres.fields.jsonb.JSONField(default=projects.enums.default_task_importance),
                ),
                (
                    'attorney_client_privilege',
                    models.BooleanField(default=False, verbose_name='Workflow Privilege Attorney Client'),
                ),
                (
                    'work_product_privilege',
                    models.BooleanField(default=False, verbose_name='Workflow Privilege Work Product'),
                ),
                (
                    'confidential_privilege',
                    models.BooleanField(default=False, verbose_name='Workflow Privilege Confidential'),
                ),
                (
                    'assigned_to_group',
                    models.ManyToManyField(
                        blank=True,
                        related_name='workflowfixture_assigned_to_workgroup',
                        to='projects.WorkGroup',
                        verbose_name='WorkGroup Workflow',
                    ),
                ),
                (
                    'assigned_to_users',
                    models.ManyToManyField(
                        blank=True,
                        related_name='workflowfixture_assigned_to_users',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Assigned To',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='workflowfixture_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created By',
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='projects_workflowfixture_last_modified_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Modified By',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='workflowfixture_organization',
                        to='authentication.Organization',
                        verbose_name='Company',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='workflowfixture_owner',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Owner',
                    ),
                ),
                (
                    'project_template',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='workflow_fixtures',
                        to='projects.ProjectTemplate',
                        verbose_name='Project template',
                    ),
                ),
                (
                    'template',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='projects.WorkflowTemplate',
                        verbose_name='Workflow template',
                    ),
                ),
                (
                    'workflow_tags',
                    models.ManyToManyField(
                        blank=True, related_name='workflowfixture_tags', to='projects.Tag', verbose_name='Workflow Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workflow Fixture',
                'verbose_name_plural': 'Workflow Fixtures',
            },
        ),
        migrations.AddField(
            model_name='taskfixture',
            name='workflow_fixture',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task_fixtures',
                to='projects.WorkflowFixture',
                verbose_name='Workflow fixture',
            ),
        ),
    ]
