# Generated by Django 2.2.17 on 2021-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_auto_20211207_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttemplate',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='taskfixture',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='workflowfixture',
            name='due_date',
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='due_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='due_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='taskfixture',
            name='due_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='due_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='workflowfixture',
            name='due_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Due Date'),
        ),

    ]
