# Generated by Django 2.2.17 on 2021-12-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_auto_20211213_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttemplate',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='taskfixture',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='workflowfixture',
            name='start_date',
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='start_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='start_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='taskfixture',
            name='start_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='start_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='workflowfixture',
            name='start_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
