# Generated by Django 2.2 on 2019-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner_email',
            field=models.EmailField(default='test@codaldemo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='owner_password',
            field=models.CharField(default='test@codaldemo.com', max_length=100),
            preserve_default=False,
        ),
    ]
