# Generated by Django 2.1.7 on 2020-05-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190425_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postmark_domain', to='customers.Domain')),
            ],
        ),
    ]
