# Generated by Django 2.2.17 on 2021-09-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_postmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('EXTERNAL_DOCS', 'External docs')], max_length=255, verbose_name='Feature')),
                ('value', models.BooleanField(default=False, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Feature',
                'unique_together': {('client', 'key')},
            },
        ),
    ]
