# Generated by Django 2.2.17 on 2021-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(choices=[('EXTERNAL_DOCS', 'External docs'), ('TASKTEMPLATE', 'Task template'), ('CUSTOM_FIELD', 'Custom field')], max_length=255, verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='value',
            field=models.BooleanField(default=False, verbose_name='Is Active?'),
        ),
    ]
