# Generated by Django 2.2.17 on 2021-10-18 20:18

from django.db import migrations, models


def remove_records(apps, schema_editor):
    Feature = apps.get_model('customers', 'Feature')
    Feature.objects.filter(key='CUSTOM_FIELD').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210910_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(choices=[('EXTERNAL_DOCS', 'External docs'), ('TASKTEMPLATE', 'Task template'), ('GLOBALCUSTOMFIELD', 'Global custom field')], max_length=255, verbose_name='Feature'),
        ),
        migrations.RunPython(
            remove_records,
            migrations.RunPython.noop,
        )
    ]
