# Generated by Django 2.2.17 on 2021-10-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20211018_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(choices=[('EXTERNAL_DOCS', 'External docs'), ('TASKTEMPLATE', 'Task template'), ('GLOBALCUSTOMFIELD', 'Global custom field'), ('WORKFLOWTEMPLATE', 'Workflow template')], max_length=255, verbose_name='Feature'),
        ),
    ]
