# Generated by Django 2.2.17 on 2021-11-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20211029_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(choices=[('EXTERNAL_DOCS', 'External docs'), ('TASKTEMPLATE', 'Task template'), ('GLOBALCUSTOMFIELD', 'Global custom field'), ('WORKFLOWTEMPLATE', 'Workflow template'), ('PROJECTTEMPLATE', 'Project template')], max_length=255, verbose_name='Feature'),
        ),
    ]
