# Generated by Django 2.1.7 on 2019-03-27 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='permission_category',
            field=models.CharField(choices=[('task', 'Task'), ('workflow', 'Workflow'), ('project', 'Project')], default='task', max_length=20, verbose_name='Permission Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersetting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_setting', to=settings.AUTH_USER_MODEL, verbose_name='User Setting'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='setting',
            field=models.CharField(db_index=True, max_length=254, verbose_name='setting'),
        ),
    ]
