# Generated by Django 2.1.7 on 2019-03-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190327_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
