# Generated by Django 2.1.7 on 2019-04-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20190405_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Is owner status'),
        ),
    ]
