# Generated by Django 2.1.7 on 2019-08-13 01:48

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='Profiles/%Y/%m/', verbose_name='Avatar'),
        ),
    ]
