# Generated by Django 2.1.7 on 2019-08-13 02:03

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20190813_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_avatar_thumb',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='Profiles/%Y/%m/', verbose_name='User Avatar Thumb'),
        ),
    ]
