# Generated by Django 2.1.7 on 2019-08-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20190813_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_user_specific',
            field=models.BooleanField(default=False, verbose_name='Is User Specific Role'),
        ),
    ]
