# Generated by Django 2.1.7 on 2019-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_group_is_user_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users_count',
            field=models.IntegerField(default=0, verbose_name='User count'),
        ),
    ]
