# Generated by Django 2.1.7 on 2019-09-04 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_group_users_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users_count',
        ),
    ]
