# Generated by Django 2.1.7 on 2019-10-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_group_users_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_company_admin',
            field=models.BooleanField(default=False, verbose_name='Is Company Admin'),
        ),
    ]
