# Generated by Django 2.1.7 on 2019-10-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_group_users_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
            ],
            options={
                'proxy': True,
                'managed': False,
            },
            bases=('authentication.invitation',),
        ),
    ]
