# Generated by Django 2.1.7 on 2019-10-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_group_can_be_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='can_be_delete',
            field=models.BooleanField(default=True, verbose_name='Can Be Delete'),
        ),
    ]
