# Generated by Django 2.1.7 on 2019-10-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20191011_0543'),
        ('authentication', '0021_adduser'),
    ]

    operations = [
    ]
