# Generated by Django 2.1.7 on 2019-10-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_auto_20191016_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=('authentication.invitation',),
        ),
    ]
