# Generated by Django 2.1.7 on 2019-11-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_merge_20191030_1231'),
        ('authentication', '0026_adduser'),
    ]

    operations = [
    ]
