# Generated by Django 2.1.7 on 2019-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_merge_20191105_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='message',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
