# Generated by Django 2.1.7 on 2019-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_auto_20191126_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
