# Generated by Django 2.1.7 on 2019-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_companyinformation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='font_color',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
