# Generated by Django 2.2.17 on 2021-09-03 15:43

from django.db import migrations, models


def add_records(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''

    Feature = apps.get_model('authentication', 'Feature')
    Feature.objects.create(
        key='EXTERNAL_DOCS',
        value=False,
    )


def remove_records(apps, schema_editor):
    Feature = apps.get_model('authentication', 'Feature')
    try:
        Feature.objects.get(
            key='EXTERNAL_DOCS',
        ).delete()
    except Feature.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0033_introslide_userintroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('GOOGLE_DOCS', 'Google docs')], max_length=255, unique=True, verbose_name='Key'),),
                ('value', models.BooleanField(default=False, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.RunPython(
            add_records,
            reverse_code=remove_records,
        )
    ]
