# Generated by Django 2.2.17 on 2021-09-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
