# Generated by Django 2.2.17 on 2021-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_delete_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission_category',
            field=models.CharField(choices=[('task', 'Task'), ('workflow', 'Workflow'), ('project', 'Project'), ('request', 'Request'), ('tasktemplate', 'Task template')], max_length=20, verbose_name='Permission Category'),
        ),
    ]
