# Generated by Django 2.1.7 on 2019-04-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'New Project'), (2, 'New Workflow'), (3, 'New Task')], default=1, verbose_name='Notification Type'),
        ),
    ]
