# Generated by Django 2.1.7 on 2019-04-05 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190403_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_type', to='notifications.NotificationType', verbose_name='Notification Name'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_type_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtype',
            unique_together={('name', 'slug')},
        ),
    ]
