# Generated by Django 2.1.7 on 2019-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notificationtype_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_url',
            field=models.URLField(blank=True, max_length=254, verbose_name='Notification Related Url'),
        ),
    ]
