# Generated by Django 2.1.7 on 2019-04-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_is_delete'),
        ('notifications', '0005_notification_notification_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultUserNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
                ('in_app_notification', models.BooleanField(default=False, verbose_name='In App Notification')),
                ('email_notification', models.BooleanField(default=False, verbose_name='Email Notification')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Group')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_notification_type_setting', to='notifications.NotificationType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
