# Generated by Django 2.1.7 on 2019-12-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='notification_category',
            field=models.CharField(blank=True, choices=[('task', 'Task'), ('workflow', 'Workflow'), ('project', 'Project'), ('account', 'Account')], max_length=100, null=True, verbose_name='Notification Category'),
        ),
    ]
