Legal_Department_Team_Member_Dict = [
    {"name": "ALL", "permission_category": "task",
     "slug": "task_all"},
    {"name": "ALL", "permission_category": "workflow",
     "slug": "workflow_all"},
    {"name": "ALL", "permission_category": "project",
     "slug": "project_all"}
]

General_Counsel_Dict = [
    {"name": "ALL", "permission_category": "task",
     "slug": "task_all"},
    {"name": "ALL", "permission_category": "workflow",
     "slug": "workflow_all"},
    {"name": "ALL", "permission_category": "project",
     "slug": "project_all"}
]
Legal_Dept_Assistant_Dict = [
    {"name": "Task View", "permission_category": "task",
     "slug": "task_task-view"},
    {"name": "Task Create", "permission_category": "task",
     "slug": "task_task-create"},
    {"name": "Task Update(EDIT)", "permission_category": "task",
     "slug": "task_task-updateedit"},
    {"name": "Task Set Importance", "permission_category": "task",
     "slug": "task_task-set-importance"},
    {"name": "Task Upload Docs", "permission_category": "task",
     "slug": "task_task-upload-docs"},
    {"name": "Task Set Due Date", "permission_category": "task",
     "slug": "task_task-set-due-date"},
    {"name": "Task Set Rank (Drag and Drop)", "permission_category": "task",
     "slug": "task_task-set-rank-drag-and-drop"},
    {"name": "Task Status Update", "permission_category": "task",
     "slug": "task_task-status-update"},
    {"name": "Task Mark Complete", "permission_category": "task",
     "slug": "task_task-mark-complete"},
    {"name": "Reject/Reassign Task", "permission_category": "task",
     "slug": "task_rejectreassign-task"},
    {"name": "Project View", "permission_category": "project",
     "slug": "project_project-view"},
    {"name": "Create/Add Task", "permission_category": "project",
     "slug": "project_createadd-task"},
]

Business_Manager_Dict = [
    {"name": "Task View", "permission_category": "task",
     "slug": "task_task-view"},
    {"name": "Task Create", "permission_category": "task",
     "slug": "task_task-create"},
    {"name": "Task Update(EDIT)", "permission_category": "task",
     "slug": "task_task-updateedit"},
    {"name": "Task Set Importance", "permission_category": "task",
     "slug": "task_task-set-importance"},
    {"name": "Task Upload Docs", "permission_category": "task",
     "slug": "task_task-upload-docs"},
    {"name": "Task Set Due Date", "permission_category": "task",
     "slug": "task_task-set-due-date"},
    {"name": "Task Set Rank (Drag and Drop)", "permission_category": "task",
     "slug": "task_task-set-rank-drag-and-drop"},
    {"name": "Task Status Update", "permission_category": "task",
     "slug": "task_task-status-update"},
    {"name": "Task Mark Complete", "permission_category": "task",
     "slug": "task_task-mark-complete"},
    {"name": "Reject/Reassign Task", "permission_category": "task",
     "slug": "task_rejectreassign-task"},
    {"name": "Project View", "permission_category": "project",
     "slug": "project_project-view"},
    {"name": "Add Team Members", "permission_category": "workflow",
     "slug": "workflow_add-team-members"},
    {"name": "Create/Add Task", "permission_category": "workflow",
     "slug": "workflow_createadd-task"},
    {"name": "Set Importance", "permission_category": "workflow",
     "slug": "workflow_set-importance"},
    {"name": "Set Due Date", "permission_category": "workflow",
     "slug": "workflow_set-due-date"},
    {"name": "Set Rank (Drag & Drop)", "permission_category": "workflow",
     "slug": "workflow_set-rank-drag-drop"},
    {"name": "Mark As Completed", "permission_category": "workflow",
     "slug": "workflow_mark-as-completed"},
]
